### ISSUE TITLE
design system

### ISSUE THREAD

**Issue by wwwApp** [drexel-pluto/pluto#107]
- [x] home
- [x] search
- [x] add friend
- [x] edit group
- [x] create group
- [x] post creation
- [x] post permission / decay
- [x] single post
- [ ] setting
- [x] group feed
- [x] profile

**_EDIT: more pages in comments below_**

@robnashed @Snibeti

please update the list as you finish the design for screens, so both designers and devs are on the same page as to which screen is ready to go

also, please open a ticket for comp match when design is ready if there isn't one already and assign either Veronica (@nicaglin) or myself(@wwwApp)

**Comment by claytercek** [comment]
also need designs for:

- [x] login
- [x] account creation

**Comment by wwwApp** [comment]
also for:

- [x] notification

**Comment by claytercek** [comment]
also for: 
- [x] add friend modal
    - basic user info (name, username, picture)
    - option to send friend request and cancel

**Comment by claytercek** [comment]
Need designs for:
- [ ] Group settings
- [ ] Post settings

(could be the same, idk)
