### ISSUE TITLE
add/edit group

### ISSUE THREAD

**Issue by wwwApp** [drexel-pluto/pluto#108]

**Comment by wwwApp** [comment]
<img width="401" alt="Screen Shot 2020-03-10 at 11 04 12 PM" src="https://user-images.githubusercontent.com/14321917/76378318-85527400-6323-11ea-9292-36ff5235aaf9.png">

a small bug... inputbox should stay fixed width and first letter is getting cut off
@nicaglin

**Comment by claytercek** [comment]
fixed this
