### ISSUE TITLE
contract book

### ISSUE THREAD

**Issue by claytercek** [drexel-pluto/pluto#11]
- [ ] Intro -> **Mike**
    - [ ] Who are we?
    - [ ] Senior project
    - [ ] Advisors
    - [ ] What is contract book / what is all this info
- [x] Overview -> **Clay**
    - [x] Product description
    - [x] Mission statement
    - [x] Idea validation (screener survey)
    - [x] Economic analysis
- [x] ~~Product -> **Clay**~~ moved to overview
    - [x] ~~Features~~
- [x] Resources -> **Clay**
    - [x] Stuff from pipeline
- [ ] Research -> **Mike**
    - [ ] Surveys
    - [ ] Competitor Analysis
- [ ] Process -> **Mike**
    - [ ] Design
        - [ ] Prototypes - Various fidelities
    - [ ] Development
        - [ ] Stack
        - [ ] Backend documentation
        - [ ] Frontend documentation -> **Clay**
- [x] Timeline -> **Clay**
    - [x] Fall Deliverables
    - [x] Winter Deliverables
    - [x] Spring Deliverables
- [x] Questions -> **Clay**
- [ ] Contact -> **Mike or Clay**

**Comment by MikeCarbone** [comment]
Everything done, worded out, live, and with a domain(?), by Friday
