### ISSUE TITLE
recipient picker for people not in groups

### ISSUE THREAD

**Issue by claytercek** [drexel-pluto/pluto#119]

**Comment by robnashed** [comment]
figma updated

**Comment by wwwApp** [comment]
<img width="404" alt="Screen Shot 2020-03-10 at 11 05 34 PM" src="https://user-images.githubusercontent.com/14321917/76378407-afa43180-6323-11ea-817b-0a58be07d0aa.png">

@robnashed 
so we're now treating all of your friends as one group, so they appear the way other group appears in permission screen. should i still update the style of everyone group per figma (without border and stuff) or is this clear enough for you (and others)?
