### ISSUE TITLE
red for login button feels weird

### ISSUE THREAD

**Issue by claytercek** [drexel-pluto/pluto#159]
![Screen Shot 2020-03-11 at 11.18.36 AM.png](https://images.zenhubusercontent.com/5ca36a52500af570674ef304/014815f7-7bf4-4908-862e-2742cb4ff893)

I feel like red should be reserved for errors / cancel actions

**Comment by claytercek** [comment]
yeah, I think this is a style we should reserve for destructive buttons

**Comment by robnashed** [comment]
i think we can switch it to carbone gradient 1

**Comment by robnashed** [comment]
pushed to origin
