### ISSUE TITLE
Liking Actions

### ISSUE THREAD

**Issue by claytercek** [drexel-pluto/pluto#65]

**Comment by wwwApp** [comment]
@claytercek 

i think its working except when you like the post from `post view` and `go back` to group feed, like counts do not update until you go out of that page and come back... so from my understanding of the issue, what you did on `addPostContent` with input box should the solution to it, but didn't work for me. i just need a break from this (lol) so... if you think you know the solution, plz let me know or feel free to take it away from me 😈
